### ISSUE TITLE
[Questions] Too magical for me :)

### ISSUE THREAD

**Issue by mikaelcom** [fbessou/angular2-schema-form-demo#10]
Hi, great project, just a question:  how the model is bound as you don't specify it into the [app.component.html](https://github.com/fbessou/angular2-schema-form-demo/blob/master/src/app/app.component.html) with the [model] attribute and it succeeds to update the model anyway when you type into the generated fields. I'm lost :disappointed: 

Another question, binding seems to require to match the hierarchy of the fields based on the fieldsets when you pass through the data but not in your demo. Am I missing something else?

**Comment by fbessou** [comment]
> Hi, great project, just a question: how the model is bound as you don't specify it into the app.component.html with the [model] attribute and it succeeds to update the model anyway when you type into the generated fields. I'm lost :disappointed:

`model` is the input data, it only provides the initial value of the form, so it can't be used to retrieve the current value of the form.
The actual value of the form is computed internally and emitted through the onChange output.

> Another question, binding seems to require to match the hierarchy of the fields based on the fieldsets when you pass through the data but not in your demo. Am I missing something else?

I don't understand this one ^^

**Comment by fbessou** [comment]
Maybe your second question is the same as #11 ?

**Comment by mikaelcom** [comment]
indeed, the second question is related to the issue #11, thx
