### ISSUE TITLE
When running the app http://localhost:3002/ it is only showing Loading..

### ISSUE THREAD

**Issue by anupamarachuri** [fbessou/angular2-schema-form-demo#2]
Hi All,

I am trying to integrated angular-schema-form with Angular 2. I have followed all the steps mentioned but I am only seeing "Loading.." on the screen.

**Comment by fbessou** [comment]
Can you post your console logs ?

**Comment by fbessou** [comment]
The version in the package.json were bad. I modified it, it should work now.

**Comment by anupamarachuri** [comment]
Hi,

I am getting the below error when doing npm start. I have replaced the package.json. deleted the existing node modules and did npm install again.

$ npm start

> angular2-schema-form-demo@1.0.0-alpha.2 start C:\angular2-schema-form-demo-master
> npm run webpack-dev-server
> 
> angular2-schema-form-demo@1.0.0-alpha.2 webpack-dev-server C:\angular2-schema-form-demo-master
> webpack-dev-server

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3002
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:82:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "webpack-dev-server"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-schema-form-demo@1.0.0-alpha.2 webpack-dev-server: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-schema-form-demo@1.0.0-alpha.2 webpack-dev-server script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-schema-form-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-schema-form-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-schema-form-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angular2-schema-form-demo-master\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-schema-form-demo@1.0.0-alpha.2 start: `npm run webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-schema-form-demo@1.0.0-alpha.2 start script 'npm run webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-schema-form-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-schema-form-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-schema-form-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angular2-schema-form-demo-master\npm-debug.log

**Comment by fbessou** [comment]
>  Error: listen EADDRINUSE 127.0.0.1:3002

Indicates that there is still an instance running in background (it's common on Windows).
You can change the port in the webpack configuration file or terminate Node in the task manager.

**Comment by anupamarachuri** [comment]
Thanks it worked :)

Is there any documentation on the schema form elements. There are some things like: widget", visibleIf which are not part of standard json schema. Also what are different widgets they are offering?

**Comment by fbessou** [comment]
Nice :)
There is a section about these things in the Readme.md of the [module](https://github.com/makinacorpus/angular2-schema-form). If you need more information, feel free to post an issue in the main project. I am aware that there are many things that need clarification.
