### ISSUE TITLE
The demo does not display anything

### ISSUE THREAD

**Issue by leostd** [fbessou/angular2-schema-form-demo#6]
Hello, I'm trying to use this library for an academic project but I can't make it work well. 

At this moment, I'm trying to start this demo. I have already followed the steps indicated in the readme.

1) git clone...
2) cd to the directory
3) npm install
4) npm start
5) localhost:3002

Then I only can see "Loading..." at the left top corner. After that, I tryed to understand what is happening with the debugger tools of Google Chrome. At the console, I found this:

1) zone.js:388 Unhandled Promise rejection: Template parse errors:...(a lot of red lines)
2) zone.js:390 Error: Uncaught (in promise): Error: Template parse errors:(…)

How can I do to make the package work? What am I doing wrong?

**Comment by fbessou** [comment]
The demo should be working again with 0ab66574ed8.
Can you check that it is working for you ?

**Comment by leostd** [comment]
Too late for read this but in any case, the demo is working correctly

2017-01-30 11:08 GMT-04:00 fbessou <notifications@github.com>:
